/* eslint-disable no-unused-vars */
export const GET_API_DATA_REQUEST = 'GET_API_DATA_REQUEST';
export const GET_API_DATA_SUCCESS = 'GET_API_DATA_SUCCESS';
export const GET_API_DATA_ERROR = 'GET_API_DATA_ERROR';
export const SELECTED_COUNTRY = 'SELECTED_COUNTRY';
export const GET_SELECTED_COUNTRY_POPULATION_DATA_REQUEST = 'GET_SELECTED_COUNTRY_POPULATION_DATA_REQUEST';
export const GET_SELECTED_COUNTRY_POPULATION_DATA_SUCCESS = 'GET_SELECTED_COUNTRY_POPULATION_DATA_SUCCESS';
export const GET_SELECTED_COUNTRY_POPULATION_DATA_ERROR = 'GET_SELECTED_COUNTRY_POPULATION_DATA_ERROR';
